// <auto-generated />
using LShopOzonWebReact.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace LShopOzonWebReact.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260623180000_ProductionTaskNovinka")]
    partial class ProductionTaskNovinka
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
        }
    }
}
